import "./globals.css";
import { Kumbh_Sans } from "next/font/google";

const kumbh = Kumbh_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Frontend Mentor | E-commerce product page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" href="./images/favicon-32x32.png" />

      <body
        className={`${kumbh.className} text-[16px] my-8 px-8 sm:px-28`}
      >
        {children}
      </body>
    </html>
  );
}
